// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rannift.proto

package ranniftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestVoteRequest struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId          int32    `protobuf:"varint,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex         int32    `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm          int32    `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3f153ff0ee8997, []int{0}
}

func (m *RequestVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRequest.Unmarshal(m, b)
}
func (m *RequestVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRequest.Marshal(b, m, deterministic)
}
func (m *RequestVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRequest.Merge(m, src)
}
func (m *RequestVoteRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRequest.Size(m)
}
func (m *RequestVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRequest proto.InternalMessageInfo

func (m *RequestVoteRequest) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateId() int32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogIndex() int32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() int32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResponse) Reset()         { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()    {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3f153ff0ee8997, []int{1}
}

func (m *RequestVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResponse.Unmarshal(m, b)
}
func (m *RequestVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResponse.Marshal(b, m, deterministic)
}
func (m *RequestVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResponse.Merge(m, src)
}
func (m *RequestVoteResponse) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResponse.Size(m)
}
func (m *RequestVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResponse proto.InternalMessageInfo

func (m *RequestVoteResponse) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type LogEntry struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term                 int32    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3f153ff0ee8997, []int{2}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type AppendEntriesRequest struct {
	Term                 int32       `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             int32       `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex         int32       `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm          int32       `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries              []*LogEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         int32       `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3f153ff0ee8997, []int{3}
}

func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(m, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() int32 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogIndex() int32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() int32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommit() int32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3f153ff0ee8997, []int{4}
}

func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(m, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*RequestVoteRequest)(nil), "ranniftpb.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "ranniftpb.RequestVoteResponse")
	proto.RegisterType((*LogEntry)(nil), "ranniftpb.LogEntry")
	proto.RegisterType((*AppendEntriesRequest)(nil), "ranniftpb.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "ranniftpb.AppendEntriesResponse")
}

func init() {
	proto.RegisterFile("rannift.proto", fileDescriptor_0c3f153ff0ee8997)
}

var fileDescriptor_0c3f153ff0ee8997 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6e, 0xf2, 0x30,
	0x14, 0xfc, 0xc2, 0x3f, 0x8f, 0x8f, 0x2e, 0x0c, 0x95, 0x22, 0xa4, 0xb6, 0x51, 0x56, 0x6c, 0xca,
	0x82, 0x9e, 0xa0, 0xaa, 0x50, 0x85, 0x8a, 0x58, 0xa4, 0xa8, 0x7b, 0x13, 0xbf, 0xa2, 0x48, 0xc4,
	0x4e, 0x6d, 0x83, 0xda, 0x5b, 0xf4, 0x34, 0xbd, 0x4e, 0xaf, 0x52, 0xc5, 0x4e, 0x22, 0x43, 0x0b,
	0x3b, 0xcf, 0xf8, 0x65, 0x32, 0x6f, 0x26, 0x81, 0xbe, 0xa4, 0x9c, 0x27, 0xaf, 0x7a, 0x92, 0x49,
	0xa1, 0x05, 0xe9, 0x16, 0x30, 0x5b, 0x87, 0x9f, 0x1e, 0x90, 0x08, 0xdf, 0x76, 0xa8, 0xf4, 0x8b,
	0xd0, 0x58, 0x1c, 0x09, 0x81, 0x86, 0x46, 0x99, 0xfa, 0x5e, 0xe0, 0x8d, 0x9b, 0x91, 0x39, 0x93,
	0x00, 0x7a, 0x31, 0xe5, 0x2c, 0x61, 0x54, 0xe3, 0x9c, 0xf9, 0x35, 0x73, 0xe5, 0x52, 0x24, 0x84,
	0xff, 0x5b, 0xaa, 0xf4, 0x42, 0x6c, 0xe6, 0x9c, 0xe1, 0xbb, 0x5f, 0x37, 0x23, 0x07, 0x5c, 0xae,
	0x52, 0xe0, 0x55, 0xfe, 0x82, 0x86, 0x55, 0x71, 0xa8, 0xf0, 0x09, 0x06, 0x07, 0x8e, 0x54, 0x26,
	0xb8, 0xc2, 0x53, 0x96, 0xf6, 0x42, 0xe3, 0xa3, 0xa4, 0x5c, 0xa3, 0xb5, 0xd4, 0x89, 0x5c, 0x2a,
	0x5c, 0x42, 0x67, 0x21, 0x36, 0x33, 0xae, 0xe5, 0x07, 0x19, 0x42, 0x33, 0x31, 0xbe, 0xac, 0x84,
	0x05, 0x95, 0x6e, 0xcd, 0xd1, 0xf5, 0xa1, 0x1d, 0x8b, 0x34, 0xa5, 0x9c, 0x99, 0x1d, 0xba, 0x51,
	0x09, 0xc3, 0x6f, 0x0f, 0x86, 0xf7, 0x59, 0x86, 0x9c, 0xe5, 0x9a, 0x09, 0xaa, 0x73, 0x89, 0x8d,
	0xa0, 0xb3, 0x45, 0xca, 0x50, 0x56, 0x71, 0x55, 0x38, 0xcf, 0x2a, 0x93, 0xb8, 0x3f, 0xce, 0xca,
	0xe5, 0xf2, 0xf5, 0x0a, 0xec, 0x66, 0xe5, 0x50, 0xe4, 0x16, 0xda, 0x68, 0x7d, 0xf8, 0xcd, 0xa0,
	0x3e, 0xee, 0x4d, 0x07, 0x93, 0xaa, 0xdb, 0x49, 0xb9, 0x78, 0x54, 0xce, 0x98, 0x82, 0x8c, 0x81,
	0x07, 0x91, 0xa6, 0x89, 0xf6, 0x5b, 0x45, 0x41, 0x0e, 0x17, 0xce, 0xe0, 0xf2, 0x68, 0xc1, 0x33,
	0x05, 0xf8, 0xd0, 0x56, 0xbb, 0x38, 0x46, 0xa5, 0x8a, 0xf0, 0x4b, 0x38, 0xfd, 0xf2, 0xe0, 0x22,
	0xb2, 0x56, 0x9e, 0x51, 0xee, 0x93, 0x18, 0xc9, 0x12, 0x7a, 0x4e, 0xb1, 0xe4, 0xca, 0xb1, 0xfa,
	0xfb, 0x13, 0x1c, 0x5d, 0x9f, 0xba, 0xb6, 0x76, 0xc2, 0x7f, 0x64, 0x05, 0xfd, 0x03, 0xa7, 0xe4,
	0xc6, 0x79, 0xe4, 0xaf, 0x92, 0x46, 0xc1, 0xe9, 0x81, 0x52, 0x75, 0xdd, 0x32, 0xff, 0xc8, 0xdd,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xf9, 0xd2, 0xa9, 0x34, 0x03, 0x00, 0x00,
}
